services:
  - type: web
    name: portfolio
    env: static
    buildCommand: cd project && npm install && npm run build
    staticPublishPath: project/dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 